apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.17.0 (a74acad)
  creationTimestamp: null
  labels:
    io.kompose.service: crs
  name: marketing-waf
  namespace: waf
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: crs
    spec:
      containers:
      - env:
        - name: ANOMALYIN
          value: "5"
        - name: ANOMALYOUT
          value: "4"
        - name: PARANOIA
          value: "1"
        - name: PROXY
          value: "1"
        - name: SERVERNAME
          value: sharpspring.com
        - name: UPSTREAM
          value: 104.154.94.123
        image: us.gcr.io/privatesharp/modsecurity-crs
        name: crs
        ports:
        - containerPort: 80
        - containerPort: 443
        resources: {}
#        volumeMounts:
#        - mountPath: /etc/modsecurity.d/owasp-crs/rules/REQUEST-900-EXCLUSION-RULES-BEFORE-CRS.conf
#          name: crs-claim0
#        - mountPath: /etc/modsecurity.d/owasp-crs/rules/RESPONSE-999-EXCLUSION-RULES-AFTER-CRS.conf
#          name: crs-claim1
      restartPolicy: Always
#      volumes:
#      - name: crs-claim0
#        persistentVolumeClaim:
#          claimName: crs-claim0
#      - name: crs-claim1
#        persistentVolumeClaim:
#          claimName: crs-claim1
status: {}
